[project]
name = "health"
version = "0.1.0"
description = "Add a short description here"
authors = ["sumanth-manchala <manchala.msr@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
python = "3.11.*"
pandas = "2.1.4.*"
seaborn = "0.13.0.*"
numpy = "1.26.2.*"
matplotlib = "3.8.2.*"
jupyter = "1.0.0.*"
scikit-learn = "1.3.2.*"
xgboost = "2.0.3.*"
catboost = "1.2.2.*"
